// ✅ Vehicle options mapping
const vehicleOptions: Record<string, Record<string, string[]>> = {
  Car: {
    'Maruti Suzuki': [
      'Alto',
      'Swift',
      'Baleno',
      'Dzire',
      'Wagon R',
      'Celerio',
      'Ignis',
      'Brezza',
      'Ertiga',
      'XL6',
      'S-Presso',
      'Ciaz',
      'Vitara Brezza',
      'Jimny',
      'Grand Vitara',
      'Invicto',
    ],
    Hyundai: [
      'i10',
      'i20',
      'Aura',
      'Verna',
      'Venue',
      'Creta',
      'Alcazar',
      'Tucson',
      'Kona Electric',
      'Ioniq 5',
      'Exter',
      'Grand i10 Nios',
    ],
    Tata: [
      'Nano',
      'Tiago',
      'Tigor',
      'Altroz',
      'Punch',
      'Nexon',
      'Harrier',
      'Safari',
      'Hexa',
      'Sumo',
      'Indica',
      'Indigo',
    ],
    Mahindra: [
      'Scorpio',
      'XUV700',
      'XUV300',
      'Thar',
      'Bolero',
      'Marazzo',
      'Alturas G4',
      'KUV100',
      'TUV300',
      'XUV400',
      'Scorpio N',
      'Scorpio Classic',
    ],
    Honda: [
      'Amaze',
      'City',
      'Jazz',
      'WR-V',
      'Elevate',
      'CR-V',
      'Civic',
      'Brio',
    ],
    Toyota: [
      'Innova Crysta',
      'Fortuner',
      'Urban Cruiser Hyryder',
      'Glanza',
      'Camry',
      'Vellfire',
      'Hilux',
      'Rumion',
      'Innova Hycross',
    ],
    Kia: ['Seltos', 'Sonet', 'Carens', 'Carnival', 'EV6'],
    Volkswagen: ['Polo', 'Vento', 'Virtus', 'Taigun', 'Tiguan'],
    Skoda: ['Rapid', 'Slavia', 'Kushaq', 'Kodiaq', 'Superb'],
    Renault: ['Kwid', 'Triber', 'Kiger', 'Duster'],
    Nissan: ['Magnite', 'Kicks', 'GT-R', 'Sunny'],
    'MG Motor': ['Hector', 'Astor', 'Gloster', 'ZS EV', 'Comet EV'],
    Citroen: ['C3', 'C5 Aircross', 'eC3'],
    Jeep: ['Compass', 'Meridian', 'Wrangler', 'Grand Cherokee'],
    BMW: [
      '3 Series',
      '5 Series',
      '7 Series',
      'X1',
      'X3',
      'X5',
      'X7',
      'i4',
      'i7',
      'iX',
    ],
    'Mercedes-Benz': [
      'A-Class',
      'C-Class',
      'E-Class',
      'S-Class',
      'GLA',
      'GLC',
      'GLE',
      'GLS',
      'EQC',
    ],
    Audi: ['A3', 'A4', 'A6', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron'],
    Volvo: ['XC40', 'XC60', 'XC90', 'S60', 'S90'],
    Jaguar: ['XE', 'XF', 'XJ', 'F-Pace', 'E-Pace', 'I-Pace'],
    'Land Rover': [
      'Range Rover',
      'Range Rover Sport',
      'Range Rover Velar',
      'Range Rover Evoque',
      'Discovery',
      'Defender',
    ],
    Porsche: ['911', 'Panamera', 'Cayenne', 'Macan', 'Taycan'],
    Lexus: ['ES', 'LS', 'NX', 'RX', 'UX', 'LM'],
    Ford: ['EcoSport', 'Endeavour', 'Figo', 'Aspire', 'Freestyle'],
    Chevrolet: ['Beat', 'Spark', 'Cruze', 'Enjoy', 'Tavera'],
    Fiat: ['Punto', 'Linea', 'Abarth', 'Urban Cross'],
    'Force Motors': ['Gurkha', 'One', 'Trax', 'Traveller'],
    Isuzu: ['D-Max', 'V-Cross', 'MU-X'],
    Mitsubishi: ['Pajero', 'Outlander', 'Montero', 'Eclipse Cross'],
  },
  Bike: {
    Hero: [
      'Splendor',
      'Passion',
      'Glamour',
      'Xtreme',
      'Achiever',
      'Karizma',
      'HF Deluxe',
      'Pleasure',
      'Maestro',
      'Destini',
      'Super Splendor',
      'Xoom',
    ],
    Honda: [
      'Shine',
      'Unicorn',
      'Activa',
      'Dio',
      'CB Hornet',
      'CB Shine',
      'Livo',
      'X-Blade',
      'CB350',
      'CB300R',
      'Africa Twin',
      'CBR650R',
    ],
    Bajaj: [
      'Pulsar',
      'Avenger',
      'CT100',
      'Platina',
      'Dominar',
      'Discover',
      'NS',
      'RS',
      'AS',
      'Chetak Electric',
    ],
    TVS: [
      'Apache',
      'Jupiter',
      'NTORQ',
      'Raider',
      'Star City',
      'Sport',
      'Radeon',
      'Scooty',
      'iQube Electric',
      'Ronin',
    ],
    Yamaha: [
      'YZF-R15',
      'FZ',
      'Fascino',
      'RayZR',
      'MT-15',
      'Aerox',
      'FZ-S',
      'FZ-X',
      'R3',
      'MT-03',
    ],
    'Royal Enfield': [
      'Classic 350',
      'Bullet 350',
      'Meteor 350',
      'Hunter 350',
      'Scram 411',
      'Himalayan',
      'Continental GT',
      'Interceptor 650',
      'Shotgun 650',
      'Super Meteor 650',
    ],
    Suzuki: [
      'Gixxer',
      'Access',
      'Burgman',
      'Intruder',
      'V-Strom',
      'Katana',
      'Hayabusa',
      'GSX-S750',
    ],
    KTM: ['Duke', 'RC', 'Adventure', '390', '250', '125', '200'],
    Mahindra: ['Gusto', 'Rodeo', 'Duro', 'Flyte', 'Centuro'],
    Jawa: ['Jawa', 'Forty Two', 'Perak', '42 Bobber'],
    Benelli: ['Imperiale 400', 'TRK 502', 'Leoncino', 'TNT 300', 'TNT 600i'],
    'Harley-Davidson': [
      'Sportster',
      'Street',
      'Iron',
      'Fat Boy',
      'Road King',
      'Heritage Classic',
      'Pan America',
    ],
    Ducati: [
      'Monster',
      'Scrambler',
      'Panigale',
      'Multistrada',
      'Diavel',
      'Streetfighter',
      'Hypermotard',
    ],
    Triumph: [
      'Bonneville',
      'Street Triple',
      'Tiger',
      'Rocket 3',
      'Trident',
      'Speed Twin',
      'Scrambler',
    ],
    'BMW Motorrad': ['G310R', 'G310GS', 'R1250GS', 'S1000RR', 'F900R', 'C400X'],
    Vespa: ['VXL', 'SXL', 'ZXL', 'Primavera', 'Sprint', 'GTS', 'Elettrica'],
    Ather: ['450X', '450 Plus', '450S'],
    'Ola Electric': ['S1 Pro', 'S1 Air', 'S1 X'],
    Revolt: ['RV400', 'RV300'],
    Ultraviolette: ['F77', 'F99'],
    Komaki: ['XT', 'XE', 'XGT', 'Venom', 'Sport'],
    Kabira: ['KM3000', 'KM4000', 'Hermes 75'],
    Ampere: ['Zeal', 'Reo', 'Vortex', 'Magnus'],
  },
  Scooter: {
    Honda: [
      'Activa',
      'Dio',
      'Aviator',
      'Activa i',
      'Activa 125',
      'Dio 125',
      'Grazia',
      'Cliq',
      'Nav',
    ],
    TVS: ['Jupiter', 'NTORQ', 'Scooty', 'Zest', 'XL', 'iQube Electric'],
    Suzuki: ['Access', 'Burgman', 'Avenis'],
    Yamaha: ['Fascino', 'RayZR', 'Aerox'],
    Hero: ['Pleasure', 'Maestro', 'Destini'],
    Vespa: ['VXL', 'SXL', 'Primavera', 'Sprint', 'GTS', 'Elettrica'],
    Aprilia: ['SR 160', 'SXR 160', 'Storm 125'],
    Mahindra: ['Gusto', 'Duro', 'Rodeo', 'Flyte'],
    Bajaj: ['Chetak', 'Chetak Electric'],
    Ather: ['450X', '450 Plus', '450S'],
    'Ola Electric': ['S1 Pro', 'S1 Air', 'S1 X'],
    'Simple Energy': ['One'],
    Bounce: ['Infinity E1'],
    'Hero Electric': ['Optima', 'Photon', 'Flash', 'NYX'],
    Okaya: ['Freedum', 'Faast', 'ClassIQ'],
    Lohia: ['Comfort', 'Humsafar', 'Ravi'],
    Gemopai: ['Astrid', 'Ryder', 'Miso'],
    BGauss: ['D15', 'C12i', 'B8'],
    Kinetic: ['Luna', 'Green', 'Zoom'],
    Peugeot: ['Django', 'Metropolis'],
    Sym: ['Miracle', 'Symphony', 'Citycom'],
    Kymco: ['Like', 'Agility', 'AK'],
  },
  Auto: {
    Bajaj: [
      'RE',
      'Maxima',
      'Compact',
      'Excel',
      'Freedom',
      'RE Optima',
      'RE Diesel',
      'RE CNG',
    ],
    Piaggio: [
      'Ape',
      'Porter',
      'Ape Xtra',
      'Ape City',
      'Ape Auto',
      'Ape E-City',
      'Ape DX',
      'Ape Xtra LDX',
    ],
    TVS: ['King', 'Auto', 'Auto+', 'King Deluxe', 'King Plus', 'King Duramax'],
    Mahindra: ['Alfa', 'Champion', 'Tourister', 'Supro', 'Jeeto', 'Treo'],
    'Force Motors': ['Traveller', 'Trump', 'Supro', 'Balwan'],
    Atul: ['Gem', 'Smart', 'Shakti', 'Gold'],
    'Scooters India': ['Vikram', 'Lambretta'],
    'E-Rickshaw Brands': [
      'Mahindra Treo',
      'Kinetic Safar',
      'Piaggio Ape E-City',
      'TVS King Electric',
      'Lohia Narain',
      'YC Electric',
      'Goenka Electric',
      'SNE Electric',
      'JS Auto',
      'Mini Metro',
      'Tuk Tuk',
      'E-Richshaw',
      'Green Rick',
      'E-Rick',
      'Saarthi',
      'Mayuri',
      'Mega',
      'Yatri',
      'Eagle',
      'J.S.',
      'Sitara',
      'Surya',
      'Hawk',
      'Rajdhani',
      'Deluxe',
      'City King',
      'Super Max',
      'Gold Star',
      'Shakti',
      'Durga',
      'Sai',
      'Ganesh',
      'Hanuman',
      'Balaji',
      'Shiv',
      'Krishna',
      'Om',
      'Trishul',
      'Bullet',
      'Rocket',
      'Thunder',
      'Flash',
      'Speedy',
      'Zoom',
      'Express',
      'Swift',
      'Rapid',
      'Quick',
      'Fast',
      'Turbo',
      'Jet',
      'Aero',
      'Space',
      'Galaxy',
      'Cosmo',
      'Universe',
      'Solar',
      'Lunar',
      'Star',
      'Sun',
      'Moon',
      'Planet',
      'Comet',
      'Meteor',
      'Orbit',
      'Satellite',
    ],
  },
  Tempo: {
    Tata: [
      'Ace',
      'Ace Gold',
      'Ace HT+',
      'Ace EV (Electric)',
      'Intra V10',
      'Intra V20',
      'Intra V30',
      'Yodha Pickup',
      'Yodha Crew Cab',
    ],
    Mahindra: [
      'Bolero Pickup 4x2',
      'Bolero Pickup Extra Long',
      'Supro Mini Van',
      'Supro Cargo Van',
      'Jeeto Plus',
      'Jeeto Strong CNG',
      'Treo Zor',
    ],
    'Ashok Leyland': ['Dost Lite', 'Dost Plus', 'Dost Strong'],
    Piaggio: ['Ape Xtra LD', 'Ape Xtra HD', 'Ape E-Xtra'],
    'Maruti Suzuki': ['Super Carry Petrol', 'Super Carry CNG'],
    'Electric Tempo': [
      'Tata Ace EV',
      'Piaggio Ape E-Xtra',
      'Mahindra Treo Zor',
      'Euler HiLoad EV',
      'Omega Seiki Rage+',
    ],
    'Force Motors': ['Traveller Tempo', 'Trump Tempo'],
    'Eicher Motors': ['Eicher Skyline', 'Eicher Pro'],
    'SML Isuzu': ['Suzu Traveller', 'SML Tempo'],
    Others: [
      'Mini Truck',
      'Pickup Van',
      'Cargo Van',
      'Goods Carrier',
      'Delivery Van',
    ],
  },
};

export { vehicleOptions };